// Get resource stocks
export const GET_RESOURCE_STOCKS_START = 'GET_RESOURCE_STOCKS_START';
export const GET_RESOURCE_STOCKS_SUCCESS = 'GET_RESOURCE_STOCKS_SUCCESS';
export const GET_RESOURCE_STOCKS_ERROR = 'GET_RESOURCE_STOCKS_SUCCESS';

// Show/hide stock adjustment form
export const SHOW_STOCK_ADJUSTMENT_FORM = 'SHOW_STOCK_ADJUSTMENT_FORM';
export const DISMISS_STOCK_ADJUSTMENT_FORM = 'DISMISS_STOCK_ADJUSTMENT_FORM';

// Get resource items
export const GET_RESOURCE_ITEMS_START = 'GET_RESOURCE_ITEMS_START';
export const GET_RESOURCE_ITEMS_SUCCESS = 'GET_RESOURCE_ITEMS_SUCCESS';
export const GET_RESOURCE_ITEMS_ERROR = 'GET_RESOURCE_ITEMS_ERROR';

// Show/hide resource item form
export const SHOW_RESOURCE_ITEM_FORM = 'SHOW_RESOURCE_ITEM_FORM';
export const DISMISS_RESOURCE_ITEM_FORM = 'DISMISS_RESOURCE_ITEM_FORM';

// Set resource item schema
export const SET_RESOURCE_SCHEMA = 'SET_RESOURCE_SCHEMA';

// Set resource adjustment schema
export const SET_RESOURCE_ADJUSTMENT_SCHEMA = 'SET_RESOURCE_ADJUSTMENT_SCHEMA';

// Get Warehouses
export const GET_WAREHOUSES_START = 'GET_WAREHOUSES_START';
export const GET_WAREHOUSES_SUCCESS = 'GET_WAREHOUSES_SUCCESS';
export const GET_WAREHOUSES_ERROR = 'GET_WAREHOUSES_ERROR';

// Show/hide warehouse form
export const SHOW_WAREHOUSE_FORM = 'SHOW_WAREHOUSE_FORM';
export const DISMISS_WAREHOUSE_FORM = 'DISMISS_WAREHOUSE_FORM';
