export const GET_RESOURCE_STOCKS_START = 'GET_RESOURCE_STOCKS_START';
export const GET_RESOURCE_STOCKS_SUCCESS = 'GET_RESOURCE_STOCKS_SUCCESS';
export const GET_RESOURCE_STOCKS_ERROR = 'GET_RESOURCE_STOCKS_SUCCESS';
export const SHOW_ADJUST_STOCK_FORM = 'SHOW_ADJUST_STOCK_FORM';
export const CANCEL_ADJUST_STOCK = 'CANCEL_ADJUST_STOCK';
